### ISSUE TITLE
Websocket client example

### ISSUE THREAD

**Issue by kracekumar** [MostAwesomeDude/txWS#28]
It may be easy to write client example using txws for twisted users, but newbies may find it difficult. Having an example will help.

**Comment by MostAwesomeDude** [comment]
Hi!

txWS doesn't provide a client. txWS only provides servers. This is because nobody should *ever* have to write a WebSockets client. If you would like a WebSockets client, please support Twisted's efforts to merge t.w.websockets upstream in ticket 4371 (http://twistedmatrix.com/trac/ticket/4173) or use Autobahn.
